// Generates ./.env.local for Scaling Inbox from the Clay workspace env +
// Supabase Management API (service-role key lookup). Prints variable NAMES
// only — never values. Safe to re-run; preserves an existing CRON_SECRET.
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { appRoot, loadEnv, parseEnvFile } from "./_env.mjs";

const { clay } = loadEnv();
const existing = parseEnvFile(path.join(appRoot, ".env.local"));

const ref = clay.SUPABASE_PROJECT_REF;
const token = clay.SUPABASE_ACCESS_TOKEN;
if (!ref || !token) throw new Error("Clay/.env.local is missing SUPABASE_PROJECT_REF or SUPABASE_ACCESS_TOKEN.");

const keysRes = await fetch(`https://api.supabase.com/v1/projects/${ref}/api-keys?reveal=true`, {
  headers: { Authorization: `Bearer ${token}` },
});
if (!keysRes.ok) throw new Error(`API key lookup failed: ${keysRes.status} ${await keysRes.text()}`);
const keys = await keysRes.json();
const serviceRole = keys.find((k) => k.name === "service_role");
const serviceKey = serviceRole?.api_key ?? serviceRole?.key;
if (!serviceKey) throw new Error("service_role key not returned by the Management API.");

const supabaseUrl = clay.VITE_SUPABASE_URL || clay.NEXT_PUBLIC_SUPABASE_URL || `https://${ref}.supabase.co`;
const anonKey = clay.VITE_SUPABASE_ANON_KEY || clay.NEXT_PUBLIC_SUPABASE_ANON_KEY;
if (!anonKey) throw new Error("Clay/.env.local is missing the Supabase anon key.");
if (!clay.ANTHROPIC_API_KEY) throw new Error("Clay/.env.local is missing ANTHROPIC_API_KEY.");
if (!clay.SMARTLEAD_API_KEY) throw new Error("Clay/.env.local is missing SMARTLEAD_API_KEY.");
if (!clay.SMARTLEAD_WEBHOOK_SECRET) throw new Error("Clay/.env.local is missing SMARTLEAD_WEBHOOK_SECRET.");

const vars = {
  NEXT_PUBLIC_SUPABASE_URL: supabaseUrl,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: anonKey,
  SUPABASE_SERVICE_ROLE_KEY: serviceKey,
  ANTHROPIC_API_KEY: clay.ANTHROPIC_API_KEY,
  // Categorization model. Haiku matches the cost plan; raise via env if needed.
  ANTHROPIC_MODEL: existing.ANTHROPIC_MODEL || "claude-haiku-4-5",
  SMARTLEAD_API_KEY: clay.SMARTLEAD_API_KEY,
  SMARTLEAD_API_BASE_URL: clay.SMARTLEAD_API_BASE_URL || "https://server.smartlead.ai/api/v1",
  SMARTLEAD_WEBHOOK_SECRET: clay.SMARTLEAD_WEBHOOK_SECRET,
  CRON_SECRET: existing.CRON_SECRET || crypto.randomBytes(24).toString("hex"),
  APP_BASE_URL: existing.APP_BASE_URL || "http://localhost:3000",
};

const body = [
  "# Scaling Inbox — local environment. Generated by scripts/setup-env.mjs; gitignored.",
  ...Object.entries(vars).map(([k, v]) => `${k}=${v}`),
  "",
].join("\n");

fs.writeFileSync(path.join(appRoot, ".env.local"), body, "utf8");
console.log("Wrote .env.local with:", Object.keys(vars).join(", "));
